### ISSUE TITLE
X not moving

### ISSUE THREAD

**Issue by NA7KR** [FYSETC/Marlin-F6#2]
I have fork the code... Trying to get it working and X will not work.
Y moves ok. 
Do you know what problem is?
Board and Wiring or I have it all moving with Marlin 2.0 down graded to try to get display working.
or any news on 2.0 version?

Any help would be good, thanks.

**Comment by NA7KR** [comment]
Are you going to merge your code back to Marlin main code?

**Comment by GerogeFu** [comment]
The Marlin 2.0 is in my plan .And you can contact me with FB messager about the drivers issue,i think it's not an issue of the firmware.And good to have your issues report.

**Comment by NA7KR** [comment]
How find you on FB there a number of George Fu's ( can find me NA7KR)

if change back to 2.0 it still works ok and prints ok

with othere version get this
Send: M122
Recv: X Y Z E E1 E2
Recv: Enabled false false false false false false
Recv: Set current 800 800 800 800 800 800
Recv: RMS current 795 1436 795 1436 795 795
Recv: MAX current 1121 2025 1121 2025 1121 1121
Recv: Run current 25/31 25/31 25/31 25/31 25/31 25/31
Recv: Hold current 12/31 12/31 12/31 12/31 12/31 12/31
Recv: CS actual 31/31 0/31 31/31 0/31 12/31 12/31
Recv: PWM scale 255 0 255 0 0 0
Recv: vsense 1=.18 0=.325 1=.18 0=.325 1=.18 1=.18
Recv: stealthChop true false true false true true
Recv: msteps 0 256 0 256 16 16
Recv: tstep 4294967295 max 4294967295 max max max
Recv: pwm
Recv: threshold 0 0 0 0 0 0
Recv: [mm/s] - - - - - -
Recv: OT prewarn true false true false false false
Recv: OT prewarn has
Recv: been triggered false false false false false false
Recv: off time 15 0 15 0 3 3
Recv: blank time 54 16 54 16 24 24
Recv: hysteresis
Recv: -end 12 -3 12 -3 -1 -1
Recv: -start 8 1 8 1 1 1
Recv: Stallguard thrs 8 8 0 0 0 0
Recv: DRVSTATUS X Y Z E E1 E2
Recv: stallguard X X
Recv: sg_result 1023 0 1023 0 0 0
Recv: fsactive X X
Recv: stst X X X X X X
Recv: olb X X X
Recv: ola X X X
Recv: s2gb X X
Recv: s2ga X X
Recv: otpw X X
Recv: ot X X
Recv: Driver registers:
Recv: X 0xFF:FF:FF:FF Bad response!
Recv: Y 0xE0:00:00:00
Recv: Z 0xFF:FF:FF:FF Bad response!
Recv: E 0x80:00:00:00
Recv: E1 0x80:0C:00:00
Recv: E2 0x80:0C:00:00
Recv:
Recv:
Recv: Testing X connection... Error: All HIGH
Recv: Testing Y connection... OK
Recv: Testing Z connection... Error: All HIGH
Recv: Testing E connection... OK
Recv: Testing E1 connection... OK
Recv: Testing E2 connection... OK
Recv: TMC CONNECTION ERROR

**Comment by GerogeFu** [comment]
George Fu is me. What drivers are you using? I will have a test in my printer

**Comment by NA7KR** [comment]
There are are more than 1 with that name.
Tmc2130

**Comment by NA7KR** [comment]
The config I am using us in fork

**Comment by GerogeFu** [comment]
Your configuration.h is weird, you 
#define EXTRUDERS 3
but there are only 1 TEMP_SENSOR_x , that will cause compile error. After i 
#define TEMP_SENSOR_0 1
#define TEMP_SENSOR_1 1
#define TEMP_SENSOR_2 1
then compile then upload then test, you see the result below , if you still have issues , i will give you the configuration.h file to you ,em,in FB messager or some other way.
![image](https://user-images.githubusercontent.com/7496375/56075684-faa68380-5df8-11e9-8218-958a8e1a3bd2.png)

**Comment by NA7KR** [comment]
I have a 3 in one head only 1 sensor and it compiles ok for me can you send the config please

**Comment by GerogeFu** [comment]
I think i know what cause your issue, you need to choose FYSETC_F6 board in ARDUINO software 
![image](https://user-images.githubusercontent.com/7496375/56102249-740bb680-5f5e-11e9-84ed-1ab264e46fee.png)
